### ISSUE TITLE
TypeError on Ubuntu 17.04

### ISSUE THREAD

**Issue by 9999dude** [timekelp/xmr-pool-choice#4]
I am getting the following error while trying to run on Ubuntu 17.04.
```
root@instance-8:~/xmr-pool-choice# python3 run.py
Gathering latency statistics...
Failed to contact the pool server: minexmr.alimabi.cn2.6% Complete
Progress |████████████████████████████████████████| 100.0% Complete
Gathering pool stats (hash rates, miners, network hashrate) ...
Progress |████████████████████████████████████████| 100.0% Complete
Traceback (most recent call last):
  File "run.py", line 45, in <module>
    hashrate_percentage = [x/network_hashrate*100 for x in hashrate]
  File "run.py", line 45, in <listcomp>
    hashrate_percentage = [x/network_hashrate*100 for x in hashrate]
TypeError: unsupported operand type(s) for /: 'str' and 'float'
```

**Comment by ZAYEC77** [comment]
had the same
